### ISSUE TITLE
ImportError after pip install

### ISSUE THREAD

**Issue by serindonnelly** [wadetb/tinynumpy#22]
I've installed tinynumpy in Python 3.4 using "pip install tinynumpy".
In interactive Python 3.4, the following happens:

```
>>> import tinynumpy
>>> dir(tinynumpy)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> from tinynumpy import tinynumpy as tnp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\tinynumpy\tinynumpy.py", line 48, in <module>
    import tinylinalg as linalg
ImportError: No module named 'tinylinalg'
```

**Comment by wadetb** [comment]
Seems to be fixed as of 1.2.1, I installed Python 3.4 and repeated these steps and did not get the error.
